version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repository-{{ checksum "pom.xml" }}
            - maven-repository-
      - run: mvn clean validate
      - run: mvn test-compile
      - run: mvn verify
      - run: rm -rf ~/.m2/repository/org/opennms
      - save_cache:
          key: maven-repository-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository  

      - run: 
          name : Build Docker Image
          command: |
            echo "Hello"