version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-dependencies-v1-{{ checksum "pom.xml" }}
            - maven-dependencies-v1-
      - run: rm -rf ~/.m2/repository/org/opennms
      - run: mvn -B clean validate
      - run: mvn -B test-compile
      - run: mvn -B verify
      - save_cache:
          key: maven-dependencies-v1-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2  
      - run:
          name : Build Docker Image
          command: |
            mvn -B dockerfile:build
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports