version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-dependencies-v2-{{ checksum "pom.xml" }}
            - maven-dependencies-v2-
      - run: rm -rf ~/.m2/repository/org/opennms
      - run: mvn -B clean validate
      - run: mvn -B test-compile
      - run: mvn -B verify
      - setup_remote_docker
      - run:
          name : Build Docker Image
          command: |
            mvn -B dockerfile:build
      - save_cache:
              key: maven-dependencies-v2-{{ checksum "pom.xml" }}
              paths:
                - ~/.m2
      - run: docker login -u ${CONTAINER_REGISTRY_LOGIN} -p ${CONTAINER_REGISTRY_PASS}
      - run:
          name: Push Docker image
          command: |
              MVN_VERSION=$(mvn -B help:evaluate -Dstyle.color=never -Dexpression=project.version -q -DforceStdout)
              echo "Version: ${MVN_VERSION}"
              docker push opennms/dummy-http-endpoint:${MVN_VERSION}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports